### ISSUE TITLE
Trying to build application resulting in "Error: Unresolved node modules"

### ISSUE THREAD

**Issue by JourneyOver** [Azure-Agst/switchrpc#80]
### Description:

Trying to build application and I keep running into `Error: Unresolved node modules` error messages and the app doesn't build at all.

This is the full error message..

```cmd
yarn build
yarn run v1.7.0
$ C:\Users\JourneyOver\Desktop\Github\switchrpc-master\app\node_modules\.bin\build
  • electron-builder version=20.19.2
  • loaded configuration file=package.json ("build" field)
  • description is missed in the package.json appPackageFile=C:\Users\JourneyOver\Desktop\Github\switchrpc-master\app\package.json
  • writing effective config file=C:\Users\JourneyOver\Desktop\Github\switchrpc-master\dist\electron-builder-effective-config.yaml
Error: Unresolved node modules: opusscript, node-opus, bufferutil, erlpack, libsodium-wrappers, sodium, uws, zlib-sync, register-scheme
    at C:\Users\JourneyOver\Desktop\Github\switchrpc-master\app\node_modules\electron-builder-lib\src\util\packageDependencies.ts:112:21
From previous event:
    at Collector.resolveUnresolvedHoisted (C:\Users\JourneyOver\Desktop\Github\switchrpc-master\app\node_modules\electron-builder-lib\src\util\packageDependencies.ts:88:81)
    at C:\Users\JourneyOver\Desktop\Github\switchrpc-master\app\node_modules\electron-builder-lib\src\util\packageDependencies.ts:83:18
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Collector.collect (C:\Users\JourneyOver\Desktop\Github\switchrpc-master\app\node_modules\electron-builder-lib\src\util\packageDependencies.ts:76:28)
    at C:\Users\JourneyOver\Desktop\Github\switchrpc-master\app\node_modules\electron-builder-lib\src\util\packageDependencies.ts:47:44
    at Generator.next (<anonymous>)
From previous event:
    at getProductionDependencies (C:\Users\JourneyOver\Desktop\Github\switchrpc-master\app\node_modules\electron-builder-lib\out\util\packageDependencies.js:130:17)
    at Lazy.<anonymous> (C:\Users\JourneyOver\Desktop\Github\switchrpc-master\app\node_modules\electron-builder-lib\src\packager.ts:113:24)
    at Generator.next (<anonymous>)
From previous event:
    at Lazy.get value [as value] (C:\Users\JourneyOver\Desktop\Github\switchrpc-master\app\node_modules\lazy-val\src\main.ts:18:23)
    at C:\Users\JourneyOver\Desktop\Github\switchrpc-master\app\node_modules\electron-builder-lib\src\util\yarn.ts:125:81
    at Generator.next (<anonymous>)
From previous event:
    at rebuild (C:\Users\JourneyOver\Desktop\Github\switchrpc-master\app\node_modules\electron-builder-lib\out\util\yarn.js:238:18)
    at C:\Users\JourneyOver\Desktop\Github\switchrpc-master\app\node_modules\electron-builder-lib\src\util\yarn.ts:20:11
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at installOrRebuild (C:\Users\JourneyOver\Desktop\Github\switchrpc-master\app\node_modules\electron-builder-lib\out\util\yarn.js:68:17)
    at C:\Users\JourneyOver\Desktop\Github\switchrpc-master\app\node_modules\electron-builder-lib\src\packager.ts:450:13
    at Generator.next (<anonymous>)
From previous event:
    at Packager.installAppDependencies (C:\Users\JourneyOver\Desktop\Github\switchrpc-master\app\node_modules\electron-builder-lib\src\packager.ts:411:70)
    at C:\Users\JourneyOver\Desktop\Github\switchrpc-master\app\node_modules\electron-builder-lib\src\packager.ts:361:20
    at Generator.next (<anonymous>)
From previous event:
    at Packager.doBuild (C:\Users\JourneyOver\Desktop\Github\switchrpc-master\app\node_modules\electron-builder-lib\src\packager.ts:337:39)
    at C:\Users\JourneyOver\Desktop\Github\switchrpc-master\app\node_modules\electron-builder-lib\src\packager.ts:313:52
    at Generator.next (<anonymous>)
    at C:\Users\JourneyOver\Desktop\Github\switchrpc-master\app\node_modules\graceful-fs\graceful-fs.js:99:16
    at C:\Users\JourneyOver\Desktop\Github\switchrpc-master\app\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:145:20)
From previous event:
    at Packager._build (C:\Users\JourneyOver\Desktop\Github\switchrpc-master\app\node_modules\electron-builder-lib\src\packager.ts:290:133)
    at C:\Users\JourneyOver\Desktop\Github\switchrpc-master\app\node_modules\electron-builder-lib\src\packager.ts:286:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Packager.build (C:\Users\JourneyOver\Desktop\Github\switchrpc-master\app\node_modules\electron-builder-lib\src\packager.ts:243:14)
    at C:\Users\JourneyOver\Desktop\Github\switchrpc-master\app\node_modules\electron-builder-lib\src\index.ts:52:40
    at Generator.next (<anonymous>)
From previous event:
    at build (C:\Users\JourneyOver\Desktop\Github\switchrpc-master\app\node_modules\electron-builder-lib\out\index.js:220:17)
    at build (C:\Users\JourneyOver\Desktop\Github\switchrpc-master\app\node_modules\electron-builder\src\builder.ts:224:10)
    at then (C:\Users\JourneyOver\Desktop\Github\switchrpc-master\app\node_modules\electron-builder\src\cli\cli.ts:46:19)
error Command failed with exit code 1.
```

I have tried to do `yarn build --win` and such as well to no avail as they throw the same error message as above..

### Steps to Reproduce:

1. Download source code
2. cd app && npm install
3. yarn build
4. Error shows up.

I'm able to use the Packager.sh script just fine, but I'd prefer to be able to build the installers.

**Comment by Azure-Agst** [comment]
oh, yeah. i forgot about that. There's a var you need to export in order for it to compile without optional dependencies. You can see it in my travis file [here](https://github.com/Azure-Agst/.travis.yml#L8). 

`$ export ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES=true` should do the trick for you.
